AllCops:
  TargetRubyVersion: 2.6.4
  Exclude:
    - 'spec/spec_helper.rb'

  # Enabled by default
  DisabledByDefault: false

  # Get CopNames for easier fix.
  DisplayCopNames: true

  # Related style guide URL. )
  DisplayStyleGuide: true

Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
   - 'spec/features/*.rb'
